image: node:8

cache:
  paths:
    - node_modules/

pages:
  stage: build
  script:
    - npm install
    - npm run build-gitlab
    - cp gitlab-robots.txt public/robots.txt
  artifacts:
    paths:
      - public
